# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'when'
description: 'when'
author: 'khs1994'
inputs:
  PCIT_WHEN_COMMIT_MESSAGE:
    description: 'check commit message'
    default: '1'
  PCIT_WHEN_BRANCH:
    description: 'branch'
    default: 'master'
  PCIT_WHEN_COMMIT_MESSAGE_SKIP:
    description: 'skip commit message'
    default: 'skip sync'
  PCIT_WHEN_COMMIT_MESSAGE_INCLUDE:
    description: 'include commit message'
    # default: 'sync xxx'
runs:
  using: 'docker'
  image: 'Dockerfile'
