version: "3.7"

x-common:
  &default-common
  labels:
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}=true
    - ${LNMP_DOMAIN:-com.khs1994.lnmp}.app.env=development

services:

  # add or override your custom service
  my-service:
    image: bash

  ## https://docs.docker.com/compose/extends/
  # php7:
  #   # change php7 default image
  #   image: username/php
  #   # open more port
  #   ports:
  #     - "9000"
  #     - "10001:10001"
  #   # add more volumes
  #   volumes:
  #     - ./app/app:/app

  # mysql:
  #   # change default volumes settings
  #   volumes:
  #     - ./data:/var/lib/mysql

  swoole:
    << : *default-common
    image: khs1994/php:7.3.0-fpm-alpine
    command:
      - php
      - /app/swoole/index.php
    ports:
      - 10001:10001
    networks:
      - backend
    volumes:
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}:cached
      - ./config/php/${LNMP_PHP_INI:-php.development.ini}:/usr/local/etc/php/php.ini:ro,cached
      - ./config/php/${LNMP_PHP_EXTRA_INI:-docker-php.ini}:/usr/local/etc/php/conf.d/docker-php.ini:ro,cached
      - ./log/php:/var/log/php:delegated
