version: "3.7"

services:

  wsl:
    build: .
    image: khs1994/wsl:latest

  wsl-php-builder-71:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_71:-7.1.26}
    image: khs1994/wsl:khs1994-wsl-php_${PHP_VERSION_71:-7.1.26}-debian-stretch_amd64

  wsl-php-builder-72:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_72:-7.2.14}
    image: khs1994/wsl:khs1994-wsl-php_${PHP_VERSION_72:-7.2.14}-debian-stretch_amd64

  wsl-php-builder-73:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_73:-7.3.1}
    image: khs1994/wsl:khs1994-wsl-php_${PHP_VERSION_72:-7.3.1}-debian-stretch_amd64

  wsl-php-builder-rhel-71:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_71:-7.1.26}
    image: khs1994/wsl:khs1994-wsl-php_${PHP_VERSION_71:-7.1.26}-centos-7_amd64

  wsl-php-builder-rhel-72:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_72:-7.2.14}
    image: khs1994/wsl:khs1994-wsl-php_${PHP_VERSION_72:-7.2.14}-centos-7_amd64
