version: "3.7"

services:

  arm64v8-php-fpm:
    build:
      context: ./7.3/alpine
      args:
        ALPINE_URL: mirrors.ustc.edu.cn
    image: ${DOCKER_HUB_USERNAME:-khs1994}/arm64v8-php:${TAG:-7.3.3}-fpm-alpine
