version: "3.5"
services:

  mysql:
    build:
      context: .
      args:
        DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
        DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security/ # security.debian.org
    image: ${DOCKER_HUB_USERNAME:-khs1994}/mysql:${TAG:-8.0.3}
