version: "3.5"
services:

  mongodb:
    build:
      context: .
      args:
        DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
        DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security/ # security.debian.org
    image: ${DOCKER_HUB_USERNAME:-khs1994}/mongo:${TAG:-3.7.2}
