# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  push:
    tags:
    branches:
    - 19.03

name: Build Docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
      if: contains( github.event.head_commit.message, '[Docs]')
    - name: docs-build
      uses: docker://pcit/vuepress
      env:
        PCIT_LOCAL_DIR: docs
      with:
        args: build
      if: contains( github.event.head_commit.message, '[Docs]')
    - name: sync-docs
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/lnmp-docs
        PCIT_KEEP_HISTORY: "1"
        PCIT_LOCAL_DIR: docs/.vuepress/dist
        PCIT_MESSAGE: Build docs by vuepress, Upload docs by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
      if: contains( github.event.head_commit.message, '[Docs]')
