name: CI

on:
  push:
    branches:
      - master
    paths:
      - '*'
      - '!/docs/*'
      # - '/.github/*'
      # - '!/drone/*'
      # - '!/kubernetes/*'
  pull_request:

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - uses: ./.github/actions/when
        with:
          PCIT_WHEN_BRANCH: "19.03"
          PCIT_WHEN_COMMIT_MESSAGE: "1"
          PCIT_WHEN_COMMIT_MESSAGE_SKIP: "skip actions"
  linux:
    needs: skip-ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: 19.03
    - name: Update docker compose
      run: |
        set -x
        docker-compose --version
        ./lnmp-docker compose --official
    - name: before_script
      run: |
        set -x
        sudo systemctl stop mysql
    - name: Up
      run: |
        set -x
        ./lnmp-docker config > docker-compose.yml
        docker-compose config -q

        docker-compose up -d $(./lnmp-docker services)
        sleep 20
        docker ps -a
        curl 127.0.0.1
        ./lnmp-docker down

        ./lnmp-docker up
    - name: Connect
      run: |
        set -x
        sleep 20
        curl 127.0.0.1
    - name: Down
      run: ./lnmp-docker down
    - name: pwsh
      run: pwsh -command "./lnmp-docker.ps1"
    - name: CLI
      run: |
        export LNMP_PATH=$PWD
        export PATH=$PWD/bin:$PATH

        set -x
        lnmp-php -v
        lnmp-composer --version

        lnmp-npm -v
        lnmp-yarn -v
  pw:
    needs: skip-ci
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: exec
      run: |
        powershell -command "./lnmp-docker.ps1"
  lwpm:
    needs: skip-ci
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: lwpm
      run: powershell -command "./windows/lnmp-windows-pm.ps1 install composer"
    - name: lwpm-add
      run: |
        echo extension=openssl >> C:\tools\php\php.ini
        powershell -command "php -i | select-string .ini"
        powershell -command "php -m"
        powershell -command "cat C:\tools\php\php.ini | select-string extension"
        powershell -command "./windows/lnmp-windows-pm.ps1 ; composer init -q"
        powershell -command "./windows/lnmp-windows-pm.ps1 ; composer config minimum-stability dev"
        powershell -command "./windows/lnmp-windows-pm.ps1 init test"
        powershell -command "./windows/lnmp-windows-pm.ps1 add openjdk"
        powershell -command "./windows/lnmp-windows-pm.ps1 install openjdk"
  lrew:
    needs: skip-ci
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: lrew-add
      run: |
        echo extension=openssl >> C:\tools\php\php.ini
        powershell -command "./windows/lnmp-windows-pm.ps1 install composer"
        powershell -command "./lnmp-docker.ps1 init test"
        powershell -command "./lnmp-docker.ps1 add harbor"
