name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - uses: ./.github/actions/when
        with:
          BRANCH: "master"
          COMMIT_MESSAGE: "1"
          COMMIT_MESSAGE_SKIP: "skip ci"
  linux:
    needs: skip-ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: 19.03
    - name: Update docker compose
      run: |
        set -x
        docker-compose --version
        ./lnmp-docker compose --official
    - name: Stop MySQL
      run: sudo systemctl stop mysql
    - name: Up
      run: |
        set -x
        ./lnmp-docker config > docker-compose.yml
        docker-compose config -q

        docker-compose up -d $(./lnmp-docker services)
        sleep 20
        docker ps -a
        curl -fsSL 127.0.0.1
        quite=true ./lnmp-docker down

        ./lnmp-docker up
    - name: Connect
      run: |
        set -x
        sleep 20
        curl -fsSL 127.0.0.1
    - name: Down
      run: ./lnmp-docker down
    - name: pwsh
      shell: pwsh
      run: ./lnmp-docker.ps1
    - name: Set ENV
      run: |
        echo ::add-path::`pwd`
        echo ::add-path::`pwd`/bin
        echo ::set-env name=LNMP_PATH::`pwd`
    - name: lnmp-CLI
      run: |
        set -x
        lnmp-php -v
        lnmp-composer --version

        lnmp-npm -v
        lnmp-yarn -v
  powershell:
    needs: skip-ci
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - shell: powershell
      run: |
        ./lnmp-docker.ps1
