name: LREW

on:
  push:
  pull_request:

jobs:
  skip-ci:
    runs-on: ubuntu-latest
    if: |
      (! (contains( github.event.head_commit.message, '[skip ci]')
      || contains( github.event.head_commit.message, '[skip action]')
      || contains( github.event.head_commit.message, '[skip actions]')
      || contains( github.event.head_commit.message, '[ci skip]')
      || contains( github.event.head_commit.message, '[actions skip]')
      || contains( github.event.head_commit.message, '[action skip]')))
    steps:
      - run: echo "build continue !"
  CI:
    runs-on: windows-latest
    needs: skip-ci
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Init
      shell: pwsh
      run: |
        echo "extension=openssl" >> C:\tools\php\php.ini
    - name: Set ENV
      run: |
        echo ::add-path::$(pwd)
        echo ::add-path::$(pwd)\windows
        echo ::add-path::C:\ProgramData\ComposerSetup\bin
        echo ::set-env name=LNMP_PATH::$(pwd)
    - name: install composer
      shell: powershell
      run: lnmp-windows-pm.ps1 install composer
    - name: lrew-init
      shell: powershell
      run: lnmp-docker.ps1 init test
    - name: lrew-init-quite
      shell: powershell
      run: |
        $QUITE=$true
        lnmp-docker.ps1 init test2
    - name: lrew-add
      shell: pwsh
      run: lnmp-docker.ps1 add etcd
    - shell: pwsh
      run: |
        ls -r vendor
